name: Create Source Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: 'RCTV Kiosk ${{ github.ref_name }}'
          body: |
            ## RCTV Kiosk Release ${{ github.ref_name }}
            
            **Build on Raspberry Pi:**
            ```bash
            curl -sSL https://raw.githubusercontent.com/gregsadetsky/rctv-tauri/main/_raspi-files/build-on-pi.sh | bash -s YOUR_TOKEN_HERE
            ```
            
            **Features:**
            - Fullscreen kiosk mode
            - Automatic URL cycling with custom durations
            - Auto-update checks every 12 hours
            - Zero user interaction required
            
            **Changes in this version:**
            - See commit history for details
          draft: false
          prerelease: false